version: 2

updates:
  - package-ecosystem: maven
    directory: /backend
    schedule: &weekly
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      maven-non-major:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule: *weekly
    open-pull-requests-limit: 5
    groups:
      web-non-major:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: /mobile/android
    schedule: *weekly
    open-pull-requests-limit: 5
    groups:
      android-non-major:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule: *weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /backend
    schedule: *weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule: *weekly
    open-pull-requests-limit: 5
