import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { MapPin, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { Button, Field } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader, Status } from "@/components/common";
import type { ShopAddress } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

export function AddressesPage() {
  const { request } = useAuth(); const { shop } = useShop(); const queryClient = useQueryClient(); const [editing, setEditing] = useState<ShopAddress | "new" | null>(null); const id = shop?.id;
  const query = useQuery({ queryKey: ["seller-addresses", id], queryFn: () => request<ShopAddress[]>(`/api/v1/seller/shops/${id}/addresses`), enabled: Boolean(id) });
  const mutate = useMutation({ mutationFn: ({ addressId, method }: { addressId: string; method: "default" | "delete" }) => request(method === "default" ? `/api/v1/seller/shops/${id}/addresses/${addressId}/default` : `/api/v1/seller/shops/${id}/addresses/${addressId}`, { method: method === "default" ? "PATCH" : "DELETE" }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["seller-addresses", id] }) });
  return <NeedShop><PageHeader eyebrow="Fulfillment origins" title="Địa chỉ gian hàng" description="Quản lý địa chỉ kinh doanh, lấy hàng và nhận hoàn trả." action={<Button onClick={() => setEditing("new")}><Plus /> Thêm địa chỉ</Button>} />{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} /> : query.data?.length ? <div className="address-grid">{query.data.map((address) => <article className="address-card" key={address.id}><div><MapPin /><Status value={address.type} />{address.defaultAddress && <span className="default-mark"><Star /> Mặc định</span>}</div><h2>{address.contactName}</h2><p>{address.phone}</p><address>{address.addressLine}<br />{[address.ward, address.district, address.province].filter(Boolean).join(", ")}</address><div className="card-actions"><Button className="button-quiet" onClick={() => setEditing(address)}><Pencil /> Sửa</Button>{!address.defaultAddress && <Button className="button-quiet" onClick={() => address.id && mutate.mutate({ addressId: address.id, method: "default" })}><Star /> Đặt mặc định</Button>}<Button className="button-quiet" aria-label="Xóa địa chỉ" onClick={() => { if (address.id && window.confirm("Xóa địa chỉ này?")) mutate.mutate({ addressId: address.id, method: "delete" }); }}><Trash2 /></Button></div></article>)}</div> : <Empty title="Chưa có địa chỉ shop" description="Thêm địa chỉ lấy hàng hoặc nhận hoàn trả để hoàn thiện vận hành." action={<Button onClick={() => setEditing("new")}><Plus /> Thêm địa chỉ</Button>} />}{mutate.error && <p className="form-error">{mutate.error.message}</p>}{editing && <AddressDrawer address={editing === "new" ? undefined : editing} shopId={id!} close={() => setEditing(null)} />}</NeedShop>;
}

type AddressForm = { type: "BUSINESS" | "PICKUP" | "RETURN"; contactName: string; phone: string; province: string; district: string; ward: string; addressLine: string; postalCode: string; defaultAddress: boolean };
function initial(address?: ShopAddress): AddressForm { return { type: (address?.type as AddressForm["type"]) ?? "PICKUP", contactName: address?.contactName ?? "", phone: address?.phone ?? "", province: address?.province ?? "", district: address?.district ?? "", ward: address?.ward ?? "", addressLine: address?.addressLine ?? "", postalCode: address?.postalCode ?? "", defaultAddress: address?.defaultAddress ?? false }; }
function AddressDrawer({ address, shopId, close }: { address?: ShopAddress; shopId: string; close: () => void }) {
  const { request } = useAuth(); const queryClient = useQueryClient(); const [form, setForm] = useState(() => initial(address));
  const save = useMutation({ mutationFn: () => request<ShopAddress>(address?.id ? `/api/v1/seller/shops/${shopId}/addresses/${address.id}` : `/api/v1/seller/shops/${shopId}/addresses`, { method: address?.id ? "PUT" : "POST", body: { ...form, countryCode: "VN", ward: form.ward.trim() || undefined, postalCode: form.postalCode.trim() || undefined } }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["seller-addresses", shopId] }); close(); } });
  return <div className="drawer-backdrop" onMouseDown={close}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="address-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-head"><div><span>{address ? "Chỉnh sửa" : "Tạo mới"}</span><h2 id="address-title">Địa chỉ gian hàng</h2><p>Thông tin phục vụ giao nhận, không dùng làm dữ liệu khách hàng.</p></div><button aria-label="Đóng" onClick={close}>×</button></div><form className="drawer-form" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="form-grid"><label className="select-field"><span>Loại địa chỉ</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as AddressForm["type"] })}><option value="BUSINESS">Kinh doanh</option><option value="PICKUP">Lấy hàng</option><option value="RETURN">Nhận trả hàng</option></select></label><Field label="Người liên hệ" required value={form.contactName} onChange={(event) => setForm({ ...form, contactName: event.target.value })} /><Field label="Số điện thoại" required inputMode="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /><Field label="Tỉnh / Thành phố" required value={form.province} onChange={(event) => setForm({ ...form, province: event.target.value })} /><Field label="Quận / Huyện" required value={form.district} onChange={(event) => setForm({ ...form, district: event.target.value })} /><Field label="Phường / Xã" value={form.ward} onChange={(event) => setForm({ ...form, ward: event.target.value })} /><Field className="full-span" label="Địa chỉ chi tiết" required value={form.addressLine} onChange={(event) => setForm({ ...form, addressLine: event.target.value })} /><Field label="Mã bưu chính" value={form.postalCode} onChange={(event) => setForm({ ...form, postalCode: event.target.value })} /><label className="check-field"><input type="checkbox" checked={form.defaultAddress} onChange={(event) => setForm({ ...form, defaultAddress: event.target.checked })} /> Đặt làm mặc định</label></div>{save.error && <p className="form-error">{save.error.message}</p>}<Button disabled={save.isPending || !form.contactName.trim() || !form.phone.trim() || !form.province.trim() || !form.district.trim() || !form.addressLine.trim()}>{save.isPending ? "Đang lưu..." : "Lưu địa chỉ"}</Button></form></aside></div>;
}
