import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { BarChart3, PackageCheck, ReceiptText, TrendingUp } from "lucide-react";
import { Button, Field } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader } from "@/components/common";
import { money } from "@/lib/format";
import type { Analytics } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

function dayInput(date: Date) { return date.toISOString().slice(0, 10); }
const analyticsDefaultTo = dayInput(new Date());
const analyticsDefaultFrom = dayInput(new Date(new Date().getTime() - 29 * 86_400_000));
export function AnalyticsPage() {
  const { request } = useAuth(); const { shop } = useShop(); const [fromInput, setFromInput] = useState(analyticsDefaultFrom); const [toInput, setToInput] = useState(analyticsDefaultTo); const [range, setRange] = useState({ from: analyticsDefaultFrom, to: analyticsDefaultTo }); const id = shop?.id;
  const from = new Date(`${range.from}T00:00:00+07:00`).toISOString(); const to = new Date(`${range.to}T23:59:59.999+07:00`).toISOString();
  const query = useQuery({ queryKey: ["seller-analytics", id, range], queryFn: () => request<Analytics>(`/api/v1/seller/shops/${id}/analytics?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`), enabled: Boolean(id) });
  return <NeedShop><PageHeader eyebrow="Business intelligence" title="Phân tích bán hàng" description="Số liệu server-side theo đơn hoàn tất và khoảng thời gian kinh doanh." /><form className="toolbar date-toolbar" onSubmit={(event) => { event.preventDefault(); setRange({ from: fromInput, to: toInput }); }}><Field label="Từ ngày" type="date" required value={fromInput} onChange={(event) => setFromInput(event.target.value)} /><Field label="Đến ngày" type="date" required value={toInput} onChange={(event) => setToInput(event.target.value)} /><Button>Cập nhật</Button></form>{query.isPending ? <Loading label="Đang tính toán báo cáo" /> : query.error ? <ErrorBlock error={query.error} /> : <><div className="metric-grid"><article><TrendingUp /><span>Doanh thu</span><strong>{money(query.data?.revenue)}</strong><small>Trong khoảng đã chọn</small></article><article><PackageCheck /><span>Đơn hoàn tất</span><strong>{query.data?.completedOrders ?? 0}</strong><small>Không tính đơn hủy / hoàn</small></article><article><ReceiptText /><span>Giá trị trung bình</span><strong>{money(query.data?.averageOrderValue)}</strong><small>Mỗi đơn hoàn tất</small></article><article><BarChart3 /><span>Sản phẩm có doanh thu</span><strong>{query.data?.topProducts?.length ?? 0}</strong><small>Được xếp hạng hiện tại</small></article></div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><h2>Sản phẩm dẫn đầu</h2><p>Xếp theo dữ liệu đơn hoàn tất.</p></div></div>{query.data?.topProducts?.length ? <div className="rank-list">{query.data.topProducts.map((item, index) => <article key={item.productId}><b>{String(index + 1).padStart(2, "0")}</b><div><strong>{item.productName}</strong><span>{item.quantity ?? 0} sản phẩm</span></div><strong>{money(item.revenue)}</strong></article>)}</div> : <Empty title="Chưa đủ dữ liệu" description="Chưa có đơn hoàn tất trong khoảng này." />}</section><section className="panel"><div className="section-heading"><div><h2>Cảnh báo tồn kho</h2><p>Biến thể đã chạm ngưỡng cảnh báo.</p></div></div>{query.data?.lowStock?.length ? <div className="compact-list">{query.data.lowStock.map((item) => <article key={item.variantId}><div><strong>{item.productName}</strong><span>{item.variantName} · {item.sku}</span></div><strong>{item.availableQuantity ?? 0} / {item.threshold ?? 0}</strong></article>)}</div> : <p className="inline-empty">Không có cảnh báo tồn kho.</p>}</section></div></>}</NeedShop>;
}
