import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { History, Search, SlidersHorizontal } from "lucide-react";
import { Button, Field } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader } from "@/components/common";
import { dateTime } from "@/lib/format";
import { availableDelta, signedQuantity } from "@/lib/inventory";
import type { Inventory, InventoryTransaction, Page } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

export function InventoryPage() {
  const { request } = useAuth(); const { shop } = useShop(); const queryClient = useQueryClient();
  const [input, setInput] = useState(""); const [search, setSearch] = useState(""); const [lowStock, setLowStock] = useState(false); const [selected, setSelected] = useState<Inventory | null>(null);
  const id = shop?.id;
  const query = useQuery({ queryKey: ["seller-inventory", id, search, lowStock], queryFn: () => request<Page<Inventory>>(`/api/v1/seller/shops/${id}/inventory?size=100&lowStock=${lowStock}${search ? `&q=${encodeURIComponent(search)}` : ""}`), enabled: Boolean(id) });
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["seller-inventory", id] });
  return <NeedShop><PageHeader eyebrow="Stock ledger" title="Kho hàng" description="Tồn khả dụng là số có thể bán; tồn giữ chỗ được backend quản lý theo giao dịch." /><form className="toolbar search-toolbar" onSubmit={(event) => { event.preventDefault(); setSearch(input.trim()); }}><label className="search-box"><Search /><input aria-label="Tìm theo sản phẩm hoặc SKU" placeholder="Tìm sản phẩm hoặc SKU" value={input} onChange={(event) => setInput(event.target.value)} /></label><Button>Tìm</Button><label className="check-field"><input type="checkbox" checked={lowStock} onChange={(event) => setLowStock(event.target.checked)} /> Chỉ sắp hết hàng</label><span>{query.data?.totalElements ?? 0} biến thể</span></form>{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} retry={() => void query.refetch()} /> : query.data?.content?.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Sản phẩm / SKU</th><th>Khả dụng</th><th>Giữ chỗ</th><th>Đã bán</th><th>Ngưỡng</th><th>Cập nhật</th><th></th></tr></thead><tbody>{query.data.content.map((item) => <InventoryRow key={item.variantId} item={item} shopId={id!} onUpdated={invalidate} onHistory={() => setSelected(item)} />)}</tbody></table></div> : <Empty title="Kho chưa có dữ liệu" description="Hãy thêm ít nhất một biến thể sản phẩm để khởi tạo tồn kho." />}{selected && <InventoryHistory item={selected} shopId={id!} close={() => setSelected(null)} />}</NeedShop>;
}

function InventoryRow({ item, shopId, onUpdated, onHistory }: { item: Inventory; shopId: string; onUpdated: () => Promise<unknown>; onHistory: () => void }) {
  const { request } = useAuth(); const [editing, setEditing] = useState(false); const [mode, setMode] = useState<"INCREASE" | "DECREASE" | "SET">("INCREASE"); const [quantity, setQuantity] = useState(""); const [threshold, setThreshold] = useState(item.lowStockThreshold?.toString() ?? ""); const [note, setNote] = useState("");
  const adjust = useMutation({ mutationFn: () => request<Inventory>(`/api/v1/seller/shops/${shopId}/inventory/${item.variantId}/adjustments`, { method: "POST", body: { mode, quantity: Number(quantity), lowStockThreshold: threshold === "" ? undefined : Number(threshold), note: note.trim() || undefined } }), onSuccess: async () => { setEditing(false); setQuantity(""); setNote(""); await onUpdated(); } });
  return <><tr className={item.lowStock ? "row-warning" : ""}><td><strong>{item.productName}</strong><small>{item.variantName} · {item.sku}</small></td><td><strong>{item.availableQuantity ?? 0}</strong></td><td>{item.reservedQuantity ?? 0}</td><td>{item.soldQuantity ?? 0}</td><td>{item.lowStockThreshold ?? 0}</td><td>{dateTime(item.updatedAt)}</td><td className="row-actions"><Button type="button" className="button-quiet" onClick={() => setEditing(!editing)}><SlidersHorizontal /> Điều chỉnh</Button><Button type="button" className="icon-button" aria-label="Xem lịch sử kho" onClick={onHistory}><History /></Button></td></tr>{editing && <tr className="inline-editor-row"><td colSpan={7}><div className="inventory-adjust"><label className="select-field"><span>Kiểu điều chỉnh</span><select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="INCREASE">Nhập thêm</option><option value="DECREASE">Giảm tồn</option><option value="SET">Đặt số lượng</option></select></label><Field label="Số lượng" type="number" min="0" required value={quantity} onChange={(event) => setQuantity(event.target.value)} /><Field label="Ngưỡng cảnh báo" type="number" min="0" value={threshold} onChange={(event) => setThreshold(event.target.value)} /><Field label="Ghi chú" value={note} onChange={(event) => setNote(event.target.value)} /><Button type="button" disabled={adjust.isPending || quantity === ""} onClick={() => adjust.mutate()}>{adjust.isPending ? "Đang cập nhật..." : "Xác nhận"}</Button></div>{adjust.error && <p className="form-error">{adjust.error.message}</p>}</td></tr>}</>;
}

function InventoryHistory({ item, shopId, close }: { item: Inventory; shopId: string; close: () => void }) {
  const { request } = useAuth(); const query = useQuery({ queryKey: ["inventory-transactions", shopId, item.variantId], queryFn: () => request<Page<InventoryTransaction>>(`/api/v1/seller/shops/${shopId}/inventory/${item.variantId}/transactions?size=100`) });
  return <div className="drawer-backdrop" role="presentation" onMouseDown={close}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="inventory-history-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-head"><div><span>Lịch sử kho</span><h2 id="inventory-history-title">{item.productName}</h2><p>{item.variantName} · {item.sku}</p></div><button aria-label="Đóng" onClick={close}>×</button></div>{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} /> : query.data?.content?.length ? <div className="timeline-list">{query.data.content.map((entry) => <article key={entry.id}><span>{dateTime(entry.createdAt)}</span><div><strong>{entry.type}</strong><p>{entry.note ?? entry.referenceType ?? "Điều chỉnh kho"}</p></div><div><b>{signedQuantity(availableDelta(entry))}</b><small>{entry.availableBefore ?? 0} → {entry.availableAfter ?? 0}</small></div></article>)}</div> : <Empty title="Chưa có biến động" description="Các lần nhập, giữ và giải phóng tồn sẽ xuất hiện tại đây." />}</aside></div>;
}
