import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowLeft, ImagePlus, Plus, Send, Trash2 } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button, Field } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader, Status } from "@/components/common";
import { money } from "@/lib/format";
import type { AttributeDefinition, Brand, Category, OptionValue, Page, ProductAttribute, ProductDetail, ProductImage, ProductOption, ProductSummary, Variant } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

const productStatuses = ["", "DRAFT", "PENDING_APPROVAL", "ACTIVE", "REJECTED", "HIDDEN", "ARCHIVED"];

export function ProductsPage() {
  const { request } = useAuth();
  const { shop } = useShop();
  const [status, setStatus] = useState("");
  const id = shop?.id;
  const query = useQuery({
    queryKey: ["seller-products", id, status],
    queryFn: () => request<Page<ProductSummary>>(`/api/v1/seller/shops/${id}/products?size=100${status ? `&status=${status}` : ""}`),
    enabled: Boolean(id),
  });
  return <NeedShop><PageHeader eyebrow="Catalog desk" title="Sản phẩm" description="Tạo, cấu hình biến thể và gửi duyệt từ một luồng thống nhất." action={<Link className="action-link" to="/products/new"><Plus /> Thêm sản phẩm</Link>} /><div className="toolbar"><label><span>Trạng thái</span><select value={status} onChange={(event) => setStatus(event.target.value)}>{productStatuses.map((item) => <option key={item || "all"} value={item}>{item ? item.replaceAll("_", " ") : "Tất cả"}</option>)}</select></label><span>{query.data?.totalElements ?? 0} sản phẩm</span></div>{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} retry={() => void query.refetch()} /> : query.data?.content?.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Sản phẩm</th><th>Danh mục</th><th>Giá từ</th><th>Đã bán</th><th>Trạng thái</th><th></th></tr></thead><tbody>{query.data.content.map((product) => <tr key={product.id}><td><div className="product-cell"><ProductThumb src={product.primaryImageUrl} /><div><strong>{product.name}</strong><small>{product.slug}</small></div></div></td><td>{product.categoryName ?? "—"}</td><td>{money(product.minimumPrice, product.currency)}</td><td>{product.soldCount ?? 0}</td><td><Status value={product.status} /></td><td><Link className="text-link" to={`/products/${product.id}`}>Chỉnh sửa</Link></td></tr>)}</tbody></table></div> : <Empty title="Chưa có sản phẩm" description="Tạo sản phẩm đầu tiên, thêm biến thể và tồn kho rồi gửi quản trị viên duyệt." action={<Link className="action-link" to="/products/new"><Plus /> Tạo sản phẩm</Link>} />}</NeedShop>;
}

function ProductThumb({ src }: { src?: string }) {
  const [failed, setFailed] = useState(false);
  return src && !failed ? <img className="product-thumb" src={src} alt="" loading="lazy" decoding="async" onError={() => setFailed(true)} /> : <span className="product-thumb product-thumb--empty">SP</span>;
}

type BaseForm = { categoryId: string; brandId: string; name: string; slug: string; shortDescription: string; description: string };
const emptyBase: BaseForm = { categoryId: "", brandId: "", name: "", slug: "", shortDescription: "", description: "" };

export function ProductEditorPage() {
  const { id } = useParams();
  const { request } = useAuth();
  const { shop } = useShop();
  const shopId = shop?.id;
  const detail = useQuery({ queryKey: ["seller-product", shopId, id], queryFn: () => request<ProductDetail>(`/api/v1/seller/shops/${shopId}/products/${id}`), enabled: Boolean(shopId && id) });
  const categories = useQuery({ queryKey: ["public-categories"], queryFn: () => request<Category[]>("/api/v1/public/categories") });
  const brands = useQuery({ queryKey: ["public-brands"], queryFn: () => request<Brand[]>("/api/v1/public/brands") });
  if (!shop) return <NeedShop><span /></NeedShop>;
  if ((id && detail.isPending) || categories.isPending || brands.isPending) return <Loading label="Đang mở hồ sơ sản phẩm" />;
  const loadError = detail.error ?? categories.error ?? brands.error;
  if (loadError) return <ErrorBlock error={loadError} />;
  const product = detail.data;
  const initial = product ? { categoryId: product.categoryId ?? "", brandId: product.brandId ?? "", name: product.name ?? "", slug: product.slug ?? "", shortDescription: product.shortDescription ?? "", description: product.description ?? "" } : emptyBase;
  return <ProductEditorForm key={product?.id ?? "new"} id={id} shopId={shop.id!} product={product} initial={initial} categoryOptions={flattenCategories(categories.data ?? [])} brands={brands.data ?? []} refresh={() => detail.refetch()} />;
}

function ProductEditorForm({ id, shopId, product, initial, categoryOptions, brands, refresh }: { id?: string; shopId: string; product?: ProductDetail; initial: BaseForm; categoryOptions: { id: string; label: string }[]; brands: Brand[]; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const navigate = useNavigate(); const queryClient = useQueryClient(); const [form, setForm] = useState<BaseForm>(initial);
  const save = useMutation({ mutationFn: () => request<ProductDetail>(id ? `/api/v1/seller/shops/${shopId}/products/${id}` : `/api/v1/seller/shops/${shopId}/products`, { method: id ? "PUT" : "POST", body: { categoryId: form.categoryId, brandId: form.brandId || undefined, name: form.name.trim(), slug: form.slug.trim() || undefined, shortDescription: form.shortDescription.trim() || undefined, description: form.description.trim() } }), onSuccess: async (saved) => { await queryClient.invalidateQueries({ queryKey: ["seller-products", shopId] }); if (!id && saved.id) navigate(`/products/${saved.id}`, { replace: true }); else await refresh(); } });
  return <><PageHeader eyebrow={id ? "Product workspace" : "New listing"} title={id ? (product?.name ?? "Sản phẩm") : "Tạo sản phẩm"} description="Thông tin bán hàng dùng chung cho storefront và ứng dụng Android." action={<Link className="back-link" to="/products"><ArrowLeft /> Danh sách</Link>} /><form className="panel form-panel" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="section-heading"><div><h2>Thông tin cơ bản</h2><p>Lưu nháp trước, sau đó bổ sung biến thể và hình ảnh.</p></div>{product && <Status value={product.status} />}</div><div className="form-grid"><Field label="Tên sản phẩm" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Field label="Slug (không bắt buộc)" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /><label className="select-field"><span>Danh mục *</span><select required value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}><option value="">Chọn danh mục</option>{categoryOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="select-field"><span>Thương hiệu</span><select value={form.brandId} onChange={(event) => setForm({ ...form, brandId: event.target.value })}><option value="">Không chọn</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><Field className="full-span" label="Mô tả ngắn" value={form.shortDescription} onChange={(event) => setForm({ ...form, shortDescription: event.target.value })} /><label className="textarea-field full-span"><span>Mô tả chi tiết *</span><textarea required rows={7} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>{save.error && <p className="form-error" role="alert">{save.error.message}</p>}<div className="form-actions"><Button disabled={save.isPending || !form.name.trim() || !form.categoryId || !form.description.trim()}>{save.isPending ? "Đang lưu..." : id ? "Lưu thay đổi" : "Tạo bản nháp"}</Button></div></form>{product?.id && <ProductConfiguration product={product} refresh={refresh} />}</>;
}

function flattenCategories(items: Category[], depth = 0): { id: string; label: string }[] {
  return items.flatMap((item) => item.id ? [{ id: item.id, label: `${"— ".repeat(depth)}${item.name ?? "Danh mục"}` }, ...flattenCategories(item.children ?? [], depth + 1)] : flattenCategories(item.children ?? [], depth + 1));
}

function ProductConfiguration({ product, refresh }: { product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const navigate = useNavigate(); const queryClient = useQueryClient(); const shopId = shop!.id!; const productId = product.id!;
  const submit = useMutation({ mutationFn: () => request<ProductDetail>(`/api/v1/seller/shops/${shopId}/products/${productId}/submit`, { method: "POST" }), onSuccess: async () => { await refresh(); await queryClient.invalidateQueries({ queryKey: ["seller-products", shopId] }); } });
  const archive = useMutation({ mutationFn: () => request<ProductDetail>(`/api/v1/seller/shops/${shopId}/products/${productId}`, { method: "DELETE" }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["seller-products", shopId] }); navigate("/products"); } });
  return <><ImageManager product={product} refresh={refresh} /><AttributeManager product={product} refresh={refresh} /><OptionManager product={product} refresh={refresh} /><VariantManager product={product} refresh={refresh} /><section className="panel publish-panel"><div><h2>Gửi kiểm duyệt</h2><p>Backend sẽ kiểm tra sản phẩm có biến thể hợp lệ và nội dung bắt buộc trước khi chuyển sang chờ duyệt.</p>{(submit.error || archive.error) && <p className="form-error" role="alert">{(submit.error ?? archive.error)?.message}</p>}</div><div><Button type="button" className="button-secondary" disabled={archive.isPending || product.status === "ARCHIVED"} onClick={() => { if (window.confirm("Lưu trữ sản phẩm này?")) archive.mutate(); }}><Archive /> Lưu trữ</Button><Button type="button" disabled={submit.isPending || !["DRAFT", "REJECTED"].includes(product.status ?? "")} onClick={() => submit.mutate()}><Send /> {submit.isPending ? "Đang gửi..." : "Gửi duyệt"}</Button></div></section></>;
}

function ImageManager({ product, refresh }: { product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const [file, setFile] = useState<File | null>(null); const [alt, setAlt] = useState(""); const [primary, setPrimary] = useState(false); const base = `/api/v1/seller/shops/${shop!.id}/products/${product.id}`;
  const upload = useMutation({ mutationFn: () => { const body = new FormData(); body.append("file", file!); return request<ProductImage>(`${base}/images?altText=${encodeURIComponent(alt)}&primary=${primary}`, { method: "POST", body }); }, onSuccess: async () => { setFile(null); setAlt(""); setPrimary(false); await refresh(); } });
  const remove = useMutation({ mutationFn: (imageId: string) => request(`${base}/images/${imageId}`, { method: "DELETE" }), onSuccess: () => refresh() });
  return <section className="panel"><div className="section-heading"><div><h2>Hình ảnh</h2><p>PNG, JPEG hoặc WebP hợp lệ; ảnh chính xuất hiện trên catalog.</p></div><span>{product.images?.length ?? 0} ảnh</span></div><div className="media-grid">{product.images?.map((image) => <figure key={image.id}><ProductThumb src={image.url} /><figcaption>{image.primary ? "Ảnh chính" : `Thứ tự ${image.sortOrder ?? 0}`}<button aria-label="Xóa ảnh" onClick={() => image.id && remove.mutate(image.id)}><Trash2 /></button></figcaption></figure>)}<label className="upload-tile"><ImagePlus /><span>{file?.name ?? "Chọn ảnh"}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label></div><div className="inline-form"><Field label="Mô tả ảnh" value={alt} onChange={(event) => setAlt(event.target.value)} /><label className="check-field"><input type="checkbox" checked={primary} onChange={(event) => setPrimary(event.target.checked)} /> Đặt làm ảnh chính</label><Button type="button" disabled={!file || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? "Đang tải..." : "Tải ảnh lên"}</Button></div>{(upload.error || remove.error) && <p className="form-error">{(upload.error ?? remove.error)?.message}</p>}</section>;
}

function AttributeManager({ product, refresh }: { product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const categoryId = product.categoryId;
  const query = useQuery({
    queryKey: ["seller-attribute-definitions", shop!.id, categoryId],
    queryFn: () => request<AttributeDefinition[]>(`/api/v1/seller/shops/${shop!.id}/products/attribute-definitions?categoryId=${categoryId}`),
    enabled: Boolean(categoryId),
  });
  return <section className="panel"><div className="section-heading"><div><h2>Thuộc tính danh mục</h2><p>Điền đủ thuộc tính bắt buộc để người mua có dữ liệu so sánh chính xác.</p></div><span>{query.data?.length ?? 0} thuộc tính</span></div>{query.isPending ? <Loading label="Đang tải thuộc tính" /> : query.error ? <ErrorBlock error={query.error} retry={() => void query.refetch()} /> : query.data?.length ? <AttributeForm definitions={query.data} values={product.attributes ?? []} product={product} refresh={refresh} /> : <p className="inline-empty">Danh mục này chưa có thuộc tính riêng.</p>}</section>;
}

function attributeState(definitions: AttributeDefinition[], current: ProductAttribute[]) {
  const values = new Map(current.flatMap((item) => item.attributeId ? [[item.attributeId, item.value ?? ""]] : []));
  return Object.fromEntries(definitions.flatMap((definition) => definition.id ? [[definition.id, values.get(definition.id) ?? ""]] : []));
}

function AttributeForm({ definitions, values, product, refresh }: { definitions: AttributeDefinition[]; values: ProductAttribute[]; product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const [form, setForm] = useState<Record<string, string>>(() => attributeState(definitions, values)); const [saved, setSaved] = useState(false);
  const missingRequired = definitions.some((definition) => definition.required && definition.id && !form[definition.id]?.trim());
  const save = useMutation({ mutationFn: () => request<ProductAttribute[]>(`/api/v1/seller/shops/${shop!.id}/products/${product.id}/attributes`, { method: "PUT", body: { values: definitions.flatMap((definition) => definition.id && form[definition.id]?.trim() ? [{ attributeId: definition.id, value: form[definition.id].trim() }] : []) } }), onSuccess: async () => { setSaved(true); await refresh(); } });
  return <><div className="form-grid attribute-grid">{definitions.map((definition) => definition.id && <label className="select-field" key={definition.id}><span>{definition.name}{definition.required ? " *" : ""}</span>{definition.valueType === "BOOLEAN" ? <select value={form[definition.id] ?? ""} onChange={(event) => { setSaved(false); setForm({ ...form, [definition.id!]: event.target.value }); }}><option value="">Chọn giá trị</option><option value="true">Có</option><option value="false">Không</option></select> : <input type={definition.valueType === "NUMBER" ? "number" : "text"} step={definition.valueType === "NUMBER" ? "any" : undefined} required={definition.required} value={form[definition.id] ?? ""} onChange={(event) => { setSaved(false); setForm({ ...form, [definition.id!]: event.target.value }); }} />}</label>)}</div>{save.error && <p className="form-error" role="alert">{save.error.message}</p>}{saved && <p className="form-success" role="status">Đã lưu thuộc tính sản phẩm.</p>}<div className="form-actions"><Button type="button" disabled={save.isPending || missingRequired} onClick={() => save.mutate()}>{save.isPending ? "Đang lưu..." : "Lưu thuộc tính"}</Button></div></>;
}

function OptionManager({ product, refresh }: { product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const [name, setName] = useState(""); const [values, setValues] = useState(""); const base = `/api/v1/seller/shops/${shop!.id}/products/${product.id}`;
  const create = useMutation({ mutationFn: () => request<ProductOption>(`${base}/options`, { method: "POST", body: { name: name.trim(), values: values.split(",").map((value, index) => ({ value: value.trim(), sortOrder: index })).filter((item) => item.value) } }), onSuccess: async () => { setName(""); setValues(""); await refresh(); } });
  return <section className="panel"><div className="section-heading"><div><h2>Tùy chọn</h2><p>Ví dụ: Màu sắc — Đen, Trắng. Có thể bỏ qua với sản phẩm một biến thể.</p></div><span>{product.options?.length ?? 0}/3 tùy chọn</span></div>{product.options?.length ? <div className="option-list">{product.options.map((option) => <OptionEditor key={option.id} option={option} base={base} refresh={refresh} />)}</div> : <p className="inline-empty">Sản phẩm chưa có tùy chọn.</p>}<div className="inline-form"><Field label="Tên tùy chọn" value={name} onChange={(event) => setName(event.target.value)} /><Field label="Giá trị (cách nhau bằng dấu phẩy)" value={values} onChange={(event) => setValues(event.target.value)} /><Button type="button" disabled={create.isPending || (product.options?.length ?? 0) >= 3 || !name.trim() || !values.split(",").some((value) => value.trim())} onClick={() => create.mutate()}><Plus /> Thêm tùy chọn</Button></div>{create.error && <p className="form-error">{create.error.message}</p>}</section>;
}

function OptionEditor({ option, base, refresh }: { option: ProductOption; base: string; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const [name, setName] = useState(option.name ?? ""); const [newValue, setNewValue] = useState(""); const optionBase = `${base}/options/${option.id}`;
  const rename = useMutation({ mutationFn: () => request<ProductOption>(optionBase, { method: "PUT", body: { name: name.trim(), sortOrder: option.sortOrder ?? 0 } }), onSuccess: () => refresh() });
  const add = useMutation({ mutationFn: () => request<OptionValue>(`${optionBase}/values`, { method: "POST", body: { value: newValue.trim(), sortOrder: option.values?.length ?? 0 } }), onSuccess: async () => { setNewValue(""); await refresh(); } });
  const remove = useMutation({ mutationFn: () => request(optionBase, { method: "DELETE" }), onSuccess: () => refresh() });
  const error = rename.error ?? add.error ?? remove.error;
  return <article className="option-card"><div className="option-card__head"><Field label="Tên tùy chọn" value={name} onChange={(event) => setName(event.target.value)} /><Button type="button" className="button-quiet" disabled={rename.isPending || !name.trim() || name.trim() === option.name} onClick={() => rename.mutate()}>Lưu tên</Button><button type="button" aria-label={`Xóa tùy chọn ${option.name}`} disabled={remove.isPending} onClick={() => { if (window.confirm(`Xóa tùy chọn ${option.name}?`)) remove.mutate(); }}><Trash2 /></button></div><div className="option-values">{option.values?.map((value) => <OptionValueEditor key={value.id} value={value} optionBase={optionBase} refresh={refresh} />)}</div><div className="option-add-value"><Field label={`Giá trị mới cho ${option.name}`} placeholder="Giá trị mới" value={newValue} onChange={(event) => setNewValue(event.target.value)} /><Button type="button" className="button-secondary" disabled={add.isPending || !newValue.trim()} onClick={() => add.mutate()}><Plus /> Thêm giá trị</Button></div>{error && <p className="form-error">{error.message}</p>}</article>;
}

function OptionValueEditor({ value, optionBase, refresh }: { value: OptionValue; optionBase: string; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const [text, setText] = useState(value.value ?? ""); const valueBase = `${optionBase}/values/${value.id}`;
  const update = useMutation({ mutationFn: () => request<OptionValue>(valueBase, { method: "PUT", body: { value: text.trim(), sortOrder: value.sortOrder ?? 0 } }), onSuccess: () => refresh() });
  const remove = useMutation({ mutationFn: () => request(valueBase, { method: "DELETE" }), onSuccess: () => refresh() });
  return <div><input aria-label={`Giá trị ${value.value}`} value={text} onChange={(event) => setText(event.target.value)} /><Button type="button" className="button-quiet" disabled={update.isPending || !text.trim() || text.trim() === value.value} onClick={() => update.mutate()}>Lưu</Button><button type="button" aria-label={`Xóa giá trị ${value.value}`} disabled={remove.isPending} onClick={() => remove.mutate()}><Trash2 /></button>{(update.error || remove.error) && <small className="form-error">{(update.error ?? remove.error)?.message}</small>}</div>;
}

function VariantManager({ product, refresh }: { product: ProductDetail; refresh: () => Promise<unknown> }) {
  return <section className="panel"><div className="section-heading"><div><h2>Biến thể bán hàng</h2><p>Mỗi SKU có giá, kích thước vận chuyển và tổ hợp tùy chọn riêng.</p></div><span>{product.variants?.length ?? 0} biến thể</span></div><div className="variant-list">{product.variants?.map((variant) => <VariantForm key={variant.id} variant={variant} product={product} refresh={refresh} />)}</div><VariantForm product={product} refresh={refresh} /></section>;
}

type VariantFormState = { sku: string; name: string; price: string; compareAtPrice: string; weightGrams: string; lengthMm: string; widthMm: string; heightMm: string; imageUrl: string; status: "ACTIVE" | "INACTIVE" | "ARCHIVED"; choices: Record<string, string> };
function variantState(variant?: Variant): VariantFormState { return { sku: variant?.sku ?? "", name: variant?.name ?? "", price: variant?.price?.toString() ?? "", compareAtPrice: variant?.compareAtPrice?.toString() ?? "", weightGrams: variant?.weightGrams?.toString() ?? "", lengthMm: variant?.lengthMm?.toString() ?? "", widthMm: variant?.widthMm?.toString() ?? "", heightMm: variant?.heightMm?.toString() ?? "", imageUrl: variant?.imageUrl ?? "", status: (variant?.status as VariantFormState["status"]) ?? "ACTIVE", choices: Object.fromEntries((variant?.selections ?? []).flatMap((item) => item.optionId && item.valueId ? [[item.optionId, item.valueId]] : [])) } }
function optionalNumber(value: string) { return value.trim() ? Number(value) : undefined; }

function VariantForm({ variant, product, refresh }: { variant?: Variant; product: ProductDetail; refresh: () => Promise<unknown> }) {
  const { request } = useAuth(); const { shop } = useShop(); const [open, setOpen] = useState(!variant); const [form, setForm] = useState(() => variantState(variant)); const base = `/api/v1/seller/shops/${shop!.id}/products/${product.id}/variants`;
  const save = useMutation({ mutationFn: () => request<Variant>(variant?.id ? `${base}/${variant.id}` : base, { method: variant?.id ? "PUT" : "POST", body: { sku: form.sku.trim(), name: form.name.trim(), price: Number(form.price), compareAtPrice: optionalNumber(form.compareAtPrice), currency: "VND", weightGrams: optionalNumber(form.weightGrams), lengthMm: optionalNumber(form.lengthMm), widthMm: optionalNumber(form.widthMm), heightMm: optionalNumber(form.heightMm), imageUrl: form.imageUrl.trim() || undefined, optionValueIds: Object.values(form.choices).filter(Boolean), status: form.status } }), onSuccess: async () => { if (!variant) setForm(variantState()); setOpen(false); await refresh(); } });
  const remove = useMutation({ mutationFn: () => request(`${base}/${variant!.id}`, { method: "DELETE" }), onSuccess: () => refresh() });
  if (variant && !open) return <div className="variant-summary"><div><strong>{variant.name}</strong><span>{variant.sku} · {money(variant.price, variant.currency)}</span></div><div><Status value={variant.status} /><Button type="button" className="button-quiet" onClick={() => setOpen(true)}>Sửa</Button></div></div>;
  return <div className="variant-editor"><div className="section-heading"><h3>{variant ? `Sửa ${variant.sku}` : "Thêm biến thể"}</h3>{variant && <button type="button" aria-label="Lưu trữ biến thể" onClick={() => remove.mutate()}><Archive /></button>}</div><div className="form-grid form-grid--compact"><Field label="SKU" required value={form.sku} onChange={(event) => setForm({ ...form, sku: event.target.value })} /><Field label="Tên biến thể" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Field label="Giá bán (VND)" required type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /><Field label="Giá so sánh" type="number" min="0" value={form.compareAtPrice} onChange={(event) => setForm({ ...form, compareAtPrice: event.target.value })} /><Field label="Khối lượng (g)" type="number" min="1" value={form.weightGrams} onChange={(event) => setForm({ ...form, weightGrams: event.target.value })} /><Field label="Dài (mm)" type="number" min="1" value={form.lengthMm} onChange={(event) => setForm({ ...form, lengthMm: event.target.value })} /><Field label="Rộng (mm)" type="number" min="1" value={form.widthMm} onChange={(event) => setForm({ ...form, widthMm: event.target.value })} /><Field label="Cao (mm)" type="number" min="1" value={form.heightMm} onChange={(event) => setForm({ ...form, heightMm: event.target.value })} /><Field className="full-span" label="URL ảnh riêng của biến thể" type="url" value={form.imageUrl} onChange={(event) => setForm({ ...form, imageUrl: event.target.value })} /><label className="select-field"><span>Trạng thái</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as VariantFormState["status"] })}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></select></label>{product.options?.map((option) => <label className="select-field" key={option.id}><span>{option.name}</span><select required value={option.id ? form.choices[option.id] ?? "" : ""} onChange={(event) => option.id && setForm({ ...form, choices: { ...form.choices, [option.id]: event.target.value } })}><option value="">Chọn giá trị</option>{option.values?.map((value) => <option key={value.id} value={value.id}>{value.value}</option>)}</select></label>)}</div>{save.error && <p className="form-error">{save.error.message}</p>}<div className="form-actions"><Button type="button" disabled={save.isPending || !form.sku.trim() || !form.name.trim() || form.price === "" || Boolean(product.options?.some((option) => option.id && !form.choices[option.id]))} onClick={() => save.mutate()}>{save.isPending ? "Đang lưu..." : variant ? "Lưu biến thể" : "Thêm biến thể"}</Button>{variant && <Button type="button" className="button-quiet" onClick={() => { setForm(variantState(variant)); setOpen(false); }}>Hủy</Button>}</div></div>;
}
