import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Field } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader, Status } from "@/components/common";
import { dateTime, money } from "@/lib/format";
import type { Page, Refund } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

const statuses = ["", "REQUESTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "REFUNDING", "REFUNDED", "CANCELLED"];
export function RefundsPage() {
  const { request } = useAuth(); const { shop } = useShop(); const queryClient = useQueryClient(); const [status, setStatus] = useState(""); const [reviewing, setReviewing] = useState<Refund | null>(null); const [note, setNote] = useState(""); const id = shop?.id;
  const query = useQuery({ queryKey: ["seller-refunds", id, status], queryFn: () => request<Page<Refund>>(`/api/v1/seller/shops/${id}/refunds?size=100${status ? `&status=${status}` : ""}`), enabled: Boolean(id) });
  const review = useMutation({ mutationFn: () => request<Refund>(`/api/v1/seller/shops/${id}/refunds/${reviewing!.id}/review`, { method: "POST", body: { note: note.trim() || undefined } }), onSuccess: async () => { setReviewing(null); setNote(""); await queryClient.invalidateQueries({ queryKey: ["seller-refunds", id] }); } });
  return <NeedShop><PageHeader eyebrow="Returns desk" title="Yêu cầu hoàn tiền" description="Seller tiếp nhận yêu cầu; quyết định tài chính cuối cùng thuộc luồng quản trị có audit." /><div className="toolbar"><label><span>Trạng thái</span><select value={status} onChange={(event) => setStatus(event.target.value)}>{statuses.map((item) => <option key={item || "all"} value={item}>{item || "Tất cả"}</option>)}</select></label><span>{query.data?.totalElements ?? 0} yêu cầu</span></div>{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} /> : query.data?.content?.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Yêu cầu</th><th>Đơn hàng</th><th>Lý do</th><th>Số tiền</th><th>Trạng thái</th><th>Tạo lúc</th><th></th></tr></thead><tbody>{query.data.content.map((item) => <tr key={item.id}><td><strong>#{item.requestNumber}</strong><small>{item.description}</small></td><td>#{item.orderNumber}</td><td>{item.reason}</td><td>{money(item.requestedAmount, item.currency)}</td><td><Status value={item.status} /></td><td>{dateTime(item.createdAt)}</td><td>{item.status === "REQUESTED" && <Button className="button-quiet" onClick={() => { setReviewing(item); setNote(""); }}>Tiếp nhận</Button>}</td></tr>)}</tbody></table></div> : <Empty title="Chưa có yêu cầu hoàn tiền" description="Yêu cầu từ khách hàng sẽ xuất hiện ở đây." />}{reviewing && <div className="drawer-backdrop" onMouseDown={() => setReviewing(null)}><aside className="drawer drawer--small" role="dialog" aria-modal="true" aria-labelledby="refund-review-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-head"><div><span>Tiếp nhận hoàn tiền</span><h2 id="refund-review-title">#{reviewing.requestNumber}</h2><p>Đơn #{reviewing.orderNumber} · {money(reviewing.requestedAmount, reviewing.currency)}</p></div><button aria-label="Đóng" onClick={() => setReviewing(null)}>×</button></div><div className="drawer-body"><p><b>{reviewing.reason}</b> — {reviewing.description}</p><ul>{reviewing.items?.map((item) => <li key={item.orderItemId}>{item.productName} · {item.variantName} × {item.quantity} — {money(item.requestedAmount, reviewing.currency)}</li>)}</ul><Field label="Ghi chú cho quản trị viên" value={note} onChange={(event) => setNote(event.target.value)} />{review.error && <p className="form-error">{review.error.message}</p>}<Button disabled={review.isPending} onClick={() => review.mutate()}>{review.isPending ? "Đang tiếp nhận..." : "Chuyển sang đang xem xét"}</Button></div></aside></div>}</NeedShop>;
}
