import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageSquareReply, Star } from "lucide-react";
import { Button } from "@shoppew/ui";
import { Empty, ErrorBlock, Loading, NeedShop, PageHeader, Status } from "@/components/common";
import { dateTime } from "@/lib/format";
import type { Page, Review } from "@/lib/types";
import { useAuth, useShop } from "@/providers";

export function ReviewsPage() {
  const { request } = useAuth(); const { shop } = useShop(); const queryClient = useQueryClient(); const [replying, setReplying] = useState<Review | null>(null); const [reply, setReply] = useState(""); const id = shop?.id;
  const query = useQuery({ queryKey: ["seller-reviews", id], queryFn: () => request<Page<Review>>(`/api/v1/seller/shops/${id}/reviews?size=100`), enabled: Boolean(id) });
  const save = useMutation({ mutationFn: () => request<Review>(`/api/v1/seller/shops/${id}/reviews/${replying!.id}/reply`, { method: "PUT", body: { reply: reply.trim() } }), onSuccess: async () => { setReplying(null); setReply(""); await queryClient.invalidateQueries({ queryKey: ["seller-reviews", id] }); } });
  return <NeedShop><PageHeader eyebrow="Customer voice" title="Đánh giá" description="Phản hồi công khai với tư cách shop; nội dung kiểm duyệt do quản trị viên phụ trách." />{query.isPending ? <Loading /> : query.error ? <ErrorBlock error={query.error} /> : query.data?.content?.length ? <div className="review-list">{query.data.content.map((review) => <article key={review.id}><div className="review-meta"><div><strong>{review.reviewerName}</strong><span>{dateTime(review.createdAt)}</span></div><div className="stars" aria-label={`${review.rating ?? 0} trên 5 sao`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} className={index < (review.rating ?? 0) ? "filled" : ""} />)}</div><Status value={review.status} /></div><p>{review.content || "Khách hàng không để lại nội dung."}</p>{review.images?.length ? <div className="review-images">{review.images.map((image) => <a key={image.id} href={image.url} target="_blank" rel="noreferrer">Xem ảnh {(image.sortOrder ?? 0) + 1}</a>)}</div> : null}{review.sellerReply ? <blockquote><strong>Phản hồi của shop</strong><p>{review.sellerReply}</p><small>{dateTime(review.sellerRepliedAt)}</small></blockquote> : <Button className="button-quiet" onClick={() => { setReplying(review); setReply(""); }}><MessageSquareReply /> Trả lời</Button>}</article>)}</div> : <Empty title="Chưa có đánh giá" description="Đánh giá từ đơn hoàn tất sẽ xuất hiện tại đây." />}{replying && <div className="drawer-backdrop" onMouseDown={() => setReplying(null)}><aside className="drawer drawer--small" role="dialog" aria-modal="true" aria-labelledby="review-reply-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-head"><div><span>Phản hồi công khai</span><h2 id="review-reply-title">Trả lời {replying.reviewerName}</h2><p>{replying.rating}/5 sao</p></div><button aria-label="Đóng" onClick={() => setReplying(null)}>×</button></div><div className="drawer-body"><p>“{replying.content || "Không có nội dung"}”</p><label className="textarea-field"><span>Nội dung phản hồi</span><textarea rows={6} required value={reply} onChange={(event) => setReply(event.target.value)} /></label>{save.error && <p className="form-error">{save.error.message}</p>}<Button disabled={save.isPending || !reply.trim()} onClick={() => save.mutate()}>{save.isPending ? "Đang đăng..." : "Đăng phản hồi"}</Button></div></aside></div>}</NeedShop>;
}
