import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Field } from "@shoppew/ui";
import { MessageSquareText, Send } from "lucide-react";
import { useState } from "react";
import { EmptyPanel, ErrorPanel, LoadingPanel, Notice, PageHeader, Pagination, SectionHeader, SelectField, StatusBadge, TextAreaField } from "@/components/common";
import { apiErrorMessage, formatBusinessTime, parseIds } from "@/lib/format";
import type { Dispute, DisputeMessageRequest, DisputePage, DisputeUpdateRequest } from "@/lib/types";
import { useAuth } from "@/providers";

export function DisputesPage() {
  const { request } = useAuth(); const queryClient = useQueryClient();
  const [statusFilter, setStatusFilter] = useState(""); const [page, setPage] = useState(0); const [selectedId, setSelectedId] = useState(""); const [decisionStatus, setDecisionStatus] = useState<DisputeUpdateRequest["status"]>("UNDER_REVIEW"); const [resolution, setResolution] = useState(""); const [message, setMessage] = useState(""); const [attachments, setAttachments] = useState(""); const [notice, setNotice] = useState(""); const [formError, setFormError] = useState("");
  const list = useQuery({ queryKey: ["admin-disputes", statusFilter, page], queryFn: () => request<DisputePage>(`/api/v1/admin/disputes?${new URLSearchParams({ ...(statusFilter ? { status: statusFilter } : {}), page: String(page), size: "20" })}`) });
  const detail = useQuery({ queryKey: ["admin-dispute", selectedId], queryFn: () => request<Dispute>(`/api/v1/admin/disputes/${selectedId}`), enabled: Boolean(selectedId) });
  const update = useMutation({ mutationFn: () => request<Dispute>(`/api/v1/admin/disputes/${selectedId}`, { method: "PUT", body: { status: decisionStatus, resolution: resolution.trim() || undefined } satisfies DisputeUpdateRequest }), onSuccess: () => { setNotice("Đã cập nhật hồ sơ tranh chấp."); setFormError(""); void queryClient.invalidateQueries({ queryKey: ["admin-disputes"] }); void queryClient.invalidateQueries({ queryKey: ["admin-dispute", selectedId] }); } });
  const send = useMutation({ mutationFn: () => request<Dispute>(`/api/v1/admin/disputes/${selectedId}/messages`, { method: "POST", body: { content: message.trim(), attachments: parseIds(attachments) } satisfies DisputeMessageRequest }), onSuccess: () => { setNotice("Tin nhắn đã được thêm vào hồ sơ."); setMessage(""); setAttachments(""); void queryClient.invalidateQueries({ queryKey: ["admin-dispute", selectedId] }); } });
  const disputes = list.data?.content ?? [];
  function select(item: Dispute) { setSelectedId(item.id ?? ""); setDecisionStatus(item.status ?? "UNDER_REVIEW"); setResolution(item.resolution ?? ""); setNotice(""); setFormError(""); }
  function submitDecision(event: React.FormEvent) { event.preventDefault(); if (["RESOLVED", "CLOSED"].includes(decisionStatus) && !resolution.trim()) { setFormError("Cần ghi kết luận trước khi giải quyết hoặc đóng hồ sơ."); return; } setFormError(""); update.mutate(); }
  return (
    <>
      <PageHeader eyebrow="Case resolution" title="Tranh chấp" description="Theo dõi toàn bộ diễn tiến, điều phối trạng thái và trao đổi trong hồ sơ có thể truy vết." />
      <div className="filter-bar filter-bar--single"><SelectField label="Trạng thái" value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(0); }}><option value="">Tất cả</option><option value="OPEN">Đang mở</option><option value="UNDER_REVIEW">Đang xem xét</option><option value="AWAITING_CUSTOMER">Chờ khách hàng</option><option value="AWAITING_SELLER">Chờ người bán</option><option value="RESOLVED">Đã giải quyết</option><option value="CLOSED">Đã đóng</option></SelectField></div>
      {notice ? <Notice>{notice}</Notice> : null}
      <div className="case-layout">
        <section>{list.isPending ? <LoadingPanel rows={7} /> : list.isError ? <ErrorPanel error={list.error} onRetry={() => void list.refetch()} /> : disputes.length === 0 ? <EmptyPanel title="Không có tranh chấp" description="Không có hồ sơ phù hợp với bộ lọc hiện tại." /> : <div className="panel case-list"><SectionHeader title="Hàng đợi hồ sơ" description={`${list.data?.totalElements ?? disputes.length} hồ sơ`} />{disputes.map((item) => <button type="button" className={selectedId === item.id ? "active" : ""} key={item.id} onClick={() => select(item)}><div><strong>{item.disputeNumber}</strong><span>Đơn {item.orderNumber}</span><small>{formatBusinessTime(item.createdAt)}</small></div><StatusBadge value={item.status} /></button>)}<Pagination page={page} totalPages={list.data?.totalPages ?? 1} onChange={setPage} disabled={list.isFetching} /></div>}</section>
        <section>{!selectedId ? <EmptyPanel title="Chọn một hồ sơ" description="Mở hồ sơ từ hàng đợi để xem nội dung và thực hiện quyết định." /> : detail.isPending ? <LoadingPanel rows={8} label="Đang tải chi tiết tranh chấp" /> : detail.isError ? <ErrorPanel error={detail.error} onRetry={() => void detail.refetch()} /> : detail.data ? <div className="panel case-detail"><SectionHeader title={detail.data.disputeNumber || "Hồ sơ tranh chấp"} description={`Đơn ${detail.data.orderNumber || "—"}`} /><dl className="detail-grid"><div><dt>Lý do</dt><dd>{detail.data.reason || "—"}</dd></div><div><dt>Trạng thái</dt><dd><StatusBadge value={detail.data.status} /></dd></div><div className="full-span"><dt>Mô tả</dt><dd>{detail.data.description || "Không có mô tả."}</dd></div></dl><form className="decision-form" onSubmit={submitDecision}><SelectField label="Trạng thái xử lý" value={decisionStatus} onChange={(event) => setDecisionStatus(event.target.value as DisputeUpdateRequest["status"])}><option value="OPEN">Đang mở</option><option value="UNDER_REVIEW">Đang xem xét</option><option value="AWAITING_CUSTOMER">Chờ khách hàng</option><option value="AWAITING_SELLER">Chờ người bán</option><option value="RESOLVED">Đã giải quyết</option><option value="CLOSED">Đã đóng</option></SelectField><TextAreaField label="Kết luận / hướng xử lý" rows={4} value={resolution} onChange={(event) => setResolution(event.target.value)} error={formError || undefined} /><Button disabled={update.isPending}>{update.isPending ? "Đang lưu…" : "Lưu quyết định"}</Button>{update.isError ? <Notice tone="error">{apiErrorMessage(update.error)}</Notice> : null}</form><section className="message-thread"><h3><MessageSquareText aria-hidden="true" /> Trao đổi hồ sơ</h3>{detail.data.messages?.length ? detail.data.messages.map((item) => <article key={item.id}><p>{item.content}</p>{item.attachments?.length ? <ul>{item.attachments.map((attachment) => <li key={attachment}><a href={attachment} target="_blank" rel="noreferrer">Tệp đính kèm</a></li>)}</ul> : null}<small>{formatBusinessTime(item.createdAt)}</small></article>) : <p className="muted">Chưa có tin nhắn.</p>}<form onSubmit={(event) => { event.preventDefault(); if (message.trim()) send.mutate(); }}><TextAreaField label="Tin nhắn mới" required rows={3} value={message} onChange={(event) => setMessage(event.target.value)} /><Field label="URL đính kèm (phân tách bằng dấu phẩy)" value={attachments} onChange={(event) => setAttachments(event.target.value)} /><Button disabled={send.isPending || !message.trim()}>{send.isPending ? "Đang gửi…" : <><Send aria-hidden="true" /> Gửi tin nhắn</>}</Button>{send.isError ? <Notice tone="error">{apiErrorMessage(send.error)}</Notice> : null}</form></section></div> : null}</section>
      </div>
    </>
  );
}
