"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Button, EmptyState, ErrorState, Field, Spinner } from "@shoppew/ui";
import { MapPin, Plus, Star, Trash2 } from "lucide-react";
import { useAuth } from "@/components/providers";
import type { Address } from "@/lib/types";

const initial = { label: "Nhà", recipientName: "", phone: "", countryCode: "VN", province: "", district: "", ward: "", addressLine: "", postalCode: "", defaultAddress: false };

export default function AddressesPage() {
  const { request } = useAuth(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [form, setForm] = useState(initial);
  const query = useQuery({ queryKey: ["addresses"], queryFn: () => request<Address[]>("/api/v1/users/me/addresses") });
  const invalidate = () => client.invalidateQueries({ queryKey: ["addresses"] });
  const create = useMutation({ mutationFn: () => request<Address>("/api/v1/users/me/addresses", { method: "POST", body: { ...form, ward: form.ward || undefined, postalCode: form.postalCode || undefined } }), onSuccess: () => { setOpen(false); setForm(initial); void invalidate(); } });
  const remove = useMutation({ mutationFn: (id: string) => request<void>(`/api/v1/users/me/addresses/${id}`, { method: "DELETE" }), onSuccess: () => void invalidate() });
  const makeDefault = useMutation({ mutationFn: (id: string) => request<Address>(`/api/v1/users/me/addresses/${id}/default`, { method: "PATCH" }), onSuccess: () => void invalidate() });
  if (query.isPending) return <Spinner label="Đang tải địa chỉ" />; if (query.error) return <ErrorState message={query.error.message} onRetry={() => void query.refetch()} />;
  return <section><div className="section-heading"><div><span className="eyebrow">Sổ địa chỉ</span><h1>Địa chỉ nhận hàng</h1><p>Địa chỉ mặc định sẽ được chọn trước khi thanh toán.</p></div><Button type="button" onClick={() => setOpen(!open)}><Plus /> Thêm địa chỉ</Button></div>{open && <form className="surface form-grid address-form" method="post" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="Nhãn địa chỉ" value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /><Field label="Người nhận" required value={form.recipientName} onChange={(e) => setForm({ ...form, recipientName: e.target.value })} /><Field label="Số điện thoại" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Field label="Tỉnh / thành phố" required value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value })} /><Field label="Quận / huyện" required value={form.district} onChange={(e) => setForm({ ...form, district: e.target.value })} /><Field label="Phường / xã" value={form.ward} onChange={(e) => setForm({ ...form, ward: e.target.value })} /><Field className="full" label="Địa chỉ chi tiết" required value={form.addressLine} onChange={(e) => setForm({ ...form, addressLine: e.target.value })} /><label className="full checkbox"><input type="checkbox" checked={form.defaultAddress} onChange={(e) => setForm({ ...form, defaultAddress: e.target.checked })} /> Đặt làm địa chỉ mặc định</label><div className="full form-actions"><Button disabled={create.isPending || !form.recipientName || !form.phone || !form.province || !form.district || !form.addressLine}>{create.isPending ? "Đang lưu..." : "Lưu địa chỉ"}</Button><Button type="button" className="sp-button--secondary" onClick={() => setOpen(false)}>Hủy</Button></div>{create.error && <p className="full notice notice--error">{create.error.message}</p>}</form>}{query.data?.length ? <div className="address-list">{query.data.map((address) => <article className="surface" key={address.id}><MapPin /><div><div><strong>{address.label || "Địa chỉ"}</strong>{address.defaultAddress && <span className="status-pill">Mặc định</span>}</div><p>{address.recipientName} · {address.phone}</p><p className="muted">{[address.addressLine, address.ward, address.district, address.province].filter(Boolean).join(", ")}</p></div><div className="row-actions">{!address.defaultAddress && <button onClick={() => address.id && makeDefault.mutate(address.id)} disabled={makeDefault.isPending}><Star /> Đặt mặc định</button>}<button className="danger-link" onClick={() => address.id && confirm("Xóa địa chỉ này?") && remove.mutate(address.id)} disabled={remove.isPending}><Trash2 /> Xóa</button></div></article>)}</div> : <EmptyState title="Chưa có địa chỉ" description="Thêm địa chỉ nhận hàng để tiếp tục checkout." />}</section>;
}
